config/routes.rb
Rails.application.routes.draw do
 
  resources :groups

  resources :friendships

  resources :profiles

  resources :friends

  resources :dashboards

  resources :locations

  devise_for :users
  get 'users/index'

  resources :users do
       collection do
         get 'imei_action'
       end
   end
  
  

   root :to => 'users#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" } 
#validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/	
#validates_attachment :image, presence: true,
 # content_type: { content_type: "image/jpeg" },
  #size: { in: 0..10.kilobytes }
#validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
#do_not_validate_attachment_file_type :image
validates_attachment :image,
  :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }

validates :firstname, presence: true
validates :lastname , presence: true
validates :phone , presence: true
validates :email , presence: true
validates :imei , presence: true
has_many :friendships
has_many :users, :through => :friendships
has_and_belongs_to_many :groups
  #def self.search(search)
  #if search
  #  find(:all, :conditions => ['friends_related_group LIKE ?', "%#{search}%"])
  #else
  #end
#end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
       params.require(:friend).permit(:firstname, :lastname, :phone,:email, :imei,:image)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for @friend, url: friends_path, html: { multipart: true } do |form| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :firstname %><br />
    <%= form.text_field :firstname %>
   </div>
<div class="field">
    <%= form.label :lastname %><br />
    <%= form.text_field :lastname %>
   </div>
<div class="field">
    <%= form.label :phone %><br />
    <%= form.text_field :phone %>
   </div>
<div class="field">
    <%= form.label :email %><br />
    <%= form.text_field :email %>
   </div>
<div class="field">
    <%= form.label :imei %><br />
    <%= form.text_field :imei %>
   </div>
   <div class="field">
    <%= form.label :image %><br />
    <%= form.file_field :image %>
   </div>
   

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1>Listing friends</h1>


<table>
  <tr>
    <th>firstname</th>
    <th>lastname</th>
    <th>phone</th>
    <th>email</th>
    <th>imei</th>
    <th>image</th>
  </tr>

<% @friends.each do |friend| %>
  <tr>
    <td><%= friend.firstname %></td>
    <td><%= friend.lastname %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.email %></td>
    <td><%= friend.imei %></td>
    <td><%= image_tag friend.image.url(:thumb) %></td>
    <td><%= link_to 'Show', friend %></td>
    <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
    <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>NewGroup</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>firstname:</strong>
  <%= @friend.firstname %>
</p>
<p>
  <strong>lastname:</strong>
  <%= @friend.lastname %>
</p>
<p>
  <strong>phone:</strong>
  <%= @friend.phone %>
</p>
<p>
  <strong>email:</strong>
  <%= @friend.email %>
</p>
<p>
  <strong>imei:</strong>
  <%= @friend.imei %>
</p>
<p>
 <strong>image:</strong>
 <%= image_tag @friend.image.url(:medium)%>
 </p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>